-- Esquema canónico PostgreSQL. Las migraciones SQLite anteriores se conservan
-- únicamente para la exportación de instalaciones legadas.

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

INSERT INTO organizations (id, name, slug)
VALUES (1, 'Default organization', 'default')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('organizations', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM organizations), 1));

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    status TEXT NOT NULL DEFAULT 'active',
    must_reset_password BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE connection_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_type TEXT NOT NULL UNIQUE DEFAULT 'RABBITMQ'
);

CREATE TABLE data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    data_source_state TEXT NOT NULL DEFAULT 'ACTIVE',
    data_source_configuration TEXT NOT NULL,
    data_source_description TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, name)
);

CREATE TABLE databases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    name TEXT NOT NULL,
    store_type TEXT NOT NULL DEFAULT '',
    json_schema TEXT NOT NULL,
    description TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, name)
);

CREATE TABLE pipeline_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    name TEXT NOT NULL,
    description TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (organization_id, name)
);

CREATE TABLE validation_schemas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    json_name TEXT NOT NULL,
    json_schema TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, json_name)
);

CREATE TABLE pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    name TEXT NOT NULL,
    group_id BIGINT REFERENCES pipeline_groups(id) ON DELETE SET NULL,
    db_id BIGINT NOT NULL REFERENCES databases(id),
    data_source_id BIGINT NOT NULL REFERENCES data_sources(id),
    validation_schema_id BIGINT NOT NULL REFERENCES validation_schemas(id),
    replicas INTEGER NOT NULL DEFAULT 1,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, name)
);

CREATE TABLE pipeline_migrations (
    id BIGINT PRIMARY KEY REFERENCES pipelines(id) ON DELETE CASCADE,
    applied_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE license_subscriptions (
    organization_id BIGINT PRIMARY KEY REFERENCES organizations(id),
    license_key TEXT NOT NULL,
    plan TEXT NOT NULL,
    state TEXT NOT NULL,
    activated_at TEXT NOT NULL,
    expires_at TEXT,
    last_checked_at TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT,
    stripe_checkout_session_id TEXT,
    stripe_subscription_status TEXT,
    stripe_payment_status TEXT,
    current_period_end TEXT,
    cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
    latest_invoice_id TEXT,
    amount_cents BIGINT,
    currency TEXT
);

CREATE TABLE plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL,
    organization_id BIGINT REFERENCES organizations(id),
    display_name TEXT NOT NULL,
    description TEXT,
    price_cents BIGINT NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    max_pipelines BIGINT NOT NULL,
    max_replicas_per_pipeline BIGINT NOT NULL,
    included_messages_monthly BIGINT NOT NULL DEFAULT 100000,
    alerts_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    premium_connectors BOOLEAN NOT NULL DEFAULT FALSE,
    multi_user BOOLEAN NOT NULL DEFAULT FALSE,
    is_custom BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_price_id TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE UNIQUE INDEX idx_plans_slug_global ON plans (slug) WHERE organization_id IS NULL;
CREATE UNIQUE INDEX idx_plans_slug_organization ON plans (organization_id, slug) WHERE organization_id IS NOT NULL;

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES organizations(id),
    user_id BIGINT,
    user_email TEXT,
    user_role TEXT,
    action TEXT NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    status_code INTEGER,
    ip_address TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE billing_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    stripe_event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    processed_ok BOOLEAN NOT NULL DEFAULT FALSE,
    last_error TEXT
);

CREATE TABLE usage_daily (
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    pipeline_id BIGINT NOT NULL REFERENCES pipelines(id),
    bucket_day TEXT NOT NULL,
    messages_received BIGINT NOT NULL DEFAULT 0,
    messages_validated BIGINT NOT NULL DEFAULT 0,
    messages_delivered BIGINT NOT NULL DEFAULT 0,
    messages_failed BIGINT NOT NULL DEFAULT 0,
    bytes_in BIGINT NOT NULL DEFAULT 0,
    bytes_out BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (organization_id, pipeline_id, bucket_day)
);

CREATE TABLE usage_monthly (
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    pipeline_id BIGINT NOT NULL REFERENCES pipelines(id),
    bucket_month TEXT NOT NULL,
    messages_received BIGINT NOT NULL DEFAULT 0,
    messages_validated BIGINT NOT NULL DEFAULT 0,
    messages_delivered BIGINT NOT NULL DEFAULT 0,
    messages_failed BIGINT NOT NULL DEFAULT 0,
    bytes_in BIGINT NOT NULL DEFAULT 0,
    bytes_out BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (organization_id, pipeline_id, bucket_month)
);

CREATE TABLE usage_monthly_quota (
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    bucket_month TEXT NOT NULL,
    reserved_messages BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (organization_id, bucket_month)
);

CREATE TABLE usage_quota_notifications (
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    bucket_month TEXT NOT NULL,
    threshold INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (organization_id, bucket_month, threshold)
);

CREATE TABLE contact_settings (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    contact_email TEXT NOT NULL,
    whatsapp_number TEXT,
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

INSERT INTO contact_settings (id, contact_email, whatsapp_number)
VALUES (1, 'info@ovidioandrade.com', NULL)
ON CONFLICT (id) DO NOTHING;

CREATE INDEX idx_users_organization_status_id_desc ON users (organization_id, status, id DESC);
CREATE INDEX idx_audit_events_organization_id_desc ON audit_events (organization_id, id DESC);
CREATE INDEX idx_billing_events_organization_id_desc ON billing_events (organization_id, id DESC);
CREATE INDEX idx_usage_monthly_organization_cycle ON usage_monthly (organization_id, bucket_month);
